# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       maui-logos

# >> macros
# << macros

Summary:    Maui-related icons and pictures
Version:    0.3.0
Release:    1
Group:      System/Base
License:    Licensed only for approved usage, see COPYING for details.
BuildArch:  noarch
URL:        http://www.maui-project.org
Source0:    %{name}-%{version}.tar.xz
Source100:  maui-logos.yaml

%description
The %{name} package contains image files which incorporate the
Maui logo.

This package and its content may not be distributed with anything but
unmodified packages from Maui Project.

See the included COPYING file for full information on copying and
redistribution of this package and its contents.


%package -n maui-splash-screen
Summary:    Maui boot splash screens
Group:      System/Base
Requires:   %{name} = %{version}-%{release}
Provides:   boot-splash-screen

%description -n maui-splash-screen
This package contains boot splash screens for Maui.


%prep
%setup -q -n %{name}-%{version}/images

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
install -D -m 644 splash-maui-startup-640x480.png %{buildroot}%{_datadir}/plymouth/splash-maui-startup-640x480.png
install -D -m 644 splash-maui-shutdown-640x480.png %{buildroot}%{_datadir}/plymouth/splash-maui-shutdown-640x480.png
ln -s splash-maui-startup-640x480.png %{buildroot}%{_datadir}/plymouth/splash.png
ln -s splash-maui-shutdown-640x480.png %{buildroot}%{_datadir}/plymouth/halt.png
ln -s splash-maui-shutdown-640x480.png %{buildroot}%{_datadir}/plymouth/poweroff.png
ln -s splash-maui-shutdown-640x480.png %{buildroot}%{_datadir}/plymouth/reboot.png

install -D -m 644 splash-maui-startup-640x480.png %{buildroot}%{_datadir}/pixmaps/system-logo-white.png

install -D -m 644 livecd-splash.png %{buildroot}%{_libdir}/anaconda-runtime/syslinux-vesa-splash.png
install -D -m 644 livecd-splash.jpg %{buildroot}%{_libdir}/anaconda-runtime/syslinux-vesa-splash.jpg
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_datadir}/pixmaps/system-logo-white.png
%{_libdir}/anaconda-runtime/syslinux-vesa-splash.png
%{_libdir}/anaconda-runtime/syslinux-vesa-splash.jpg
# >> files
# << files

%files -n maui-splash-screen
%defattr(-,root,root,-)
%{_datadir}/plymouth/splash-maui-startup-640x480.png
%{_datadir}/plymouth/splash-maui-shutdown-640x480.png
%{_datadir}/plymouth/splash.png
%{_datadir}/plymouth/halt.png
%{_datadir}/plymouth/poweroff.png
%{_datadir}/plymouth/reboot.png
# >> files maui-splash-screen
# << files maui-splash-screen
